### ISSUE TITLE
track windows in focus.

### ISSUE THREAD

**Issue by thrombe** [consumer-ai-lab/gravishken#40]
keep checking in a loop what windows are focused. if any unknown window is focused, forcefully focus the application and warn the user.

**Comment by thrombe** [comment]
somehow need to make sure the window is not important before we kill it :P

**Comment by Prathamesh314** [comment]
"even "do you want to quit without saving" prompt windows get killed."

This is only for unknown and extra not needed windows. Right?

**Comment by thrombe** [comment]
@Prathamesh314 

no. any app including the test apps (ms word, powerpoint, etc)

**Comment by Prathamesh314** [comment]
Sure
